import type { Metadata } from 'next'
import Link from 'next/link'
import AdUnit from '@/components/AdUnit'

export const metadata: Metadata = {
  title: 'Free Printable Chore Chart for Kids — Download PDF Instantly',
  description:
    'Download a free printable chore chart for kids. Customize with your child\'s name, choose age-appropriate chores, and print in seconds. No login, no cost.',
  keywords: [
    'free printable chore chart',
    'printable chore chart for kids',
    'chore chart PDF',
    'weekly chore chart printable',
    'free kids chore chart download',
  ],
}

const themes = [
  { emoji: '🌈', name: 'Rainbow', desc: 'Bright and colourful — great for toddlers.' },
  { emoji: '🦕', name: 'Dinosaurs', desc: 'Perfect for little dino fans.' },
  { emoji: '🚀', name: 'Space', desc: 'Blast off with planets and stars.' },
  { emoji: '🐾', name: 'Animals', desc: 'Warm, earthy tones with cute animals.' },
  { emoji: '🌸', name: 'Minimal Pastel', desc: 'Soft, modern look for all ages.' },
  { emoji: '✏️', name: 'Neutral Clean', desc: 'Minimal, clean, works for any child.' },
]

const faqs = [
  {
    q: 'Is this chore chart really free?',
    a: 'Yes, completely free. No ads, no login, no watermarks. Just open the generator and download your chart.',
  },
  {
    q: 'What format does the download come in?',
    a: 'PDF format. Works on all printers, phones, and tablets. Supports both A4 and US Letter paper sizes.',
  },
  {
    q: 'Can I edit the chore chart after downloading?',
    a: 'The generator lets you fully customise before downloading. If you need changes, just come back and regenerate — it takes seconds.',
  },
  {
    q: 'How do I print the chore chart?',
    a: 'Download the PDF and open it with any PDF viewer, then print. Or click the Print button directly in the generator to skip the download step.',
  },
  {
    q: 'Can I use this chart for multiple children?',
    a: 'Yes! Simply generate a separate chart for each child with their own name, age-matched chores, and theme. Each downloads as its own PDF.',
  },
]

export default function FreePrintablePage() {
  return (
    <>
      {/* Hero */}
      <div className="bg-gradient-to-br from-purple-600 to-indigo-600 text-white py-16 px-4">
        <div className="max-w-3xl mx-auto text-center">
          <p className="text-purple-200 font-bold text-sm uppercase tracking-widest mb-3">100% Free — No Login</p>
          <h1 className="font-display text-4xl md:text-5xl mb-4 leading-tight">
            Free Printable Chore Chart for Kids
          </h1>
          <p className="text-purple-100 text-lg max-w-xl mx-auto mb-8 leading-relaxed">
            Download a beautiful, custom chore chart as a PDF in seconds.
            Pick your child&apos;s age, choose chores, add a reward — print today.
          </p>
          <Link
            href="/chore-chart-generator"
            className="inline-block bg-white text-purple-700 font-bold px-10 py-4 rounded-2xl text-lg hover:bg-purple-50 transition-colors shadow-lg"
          >
            📋 Build My Free Chart Now
          </Link>
          <p className="mt-3 text-purple-300 text-sm">Instant PDF · A4 &amp; US Letter · No watermarks</p>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 py-14 space-y-14">

        {/* What's included */}
        <section>
          <h2 className="font-display text-3xl text-gray-800 mb-4">What's Included in Your Free Chart</h2>
          <p className="text-gray-600 leading-relaxed mb-6">
            Every chart generated by Planivor is fully personalised and print-ready. Here&apos;s what you get:
          </p>
          <div className="grid sm:grid-cols-2 gap-4">
            {[
              { emoji: '👤', text: 'Your child\'s name on the chart header' },
              { emoji: '📅', text: 'A full 7-day weekly grid (Mon–Sun)' },
              { emoji: '✅', text: 'Up to 7 age-appropriate chores with emojis' },
              { emoji: '🏆', text: 'A reward goal section at the bottom' },
              { emoji: '✍️', text: 'Parent signature and star counter lines' },
              { emoji: '🎨', text: 'Your chosen theme — 6 options available' },
            ].map(item => (
              <div key={item.text} className="flex items-start gap-3 bg-white rounded-xl p-4 border border-gray-100">
                <span className="text-2xl">{item.emoji}</span>
                <p className="text-gray-700 font-semibold text-sm">{item.text}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Themes */}
        <section>
          <h2 className="font-display text-3xl text-gray-800 mb-2">6 Free Chart Themes</h2>
          <p className="text-gray-600 mb-6">Choose the theme your child loves most:</p>
          <div className="grid sm:grid-cols-2 md:grid-cols-3 gap-4">
            {themes.map(t => (
              <div key={t.name} className="bg-white rounded-2xl border border-gray-100 p-5 text-center">
                <div className="text-4xl mb-2">{t.emoji}</div>
                <h3 className="font-bold text-gray-800 mb-1">{t.name}</h3>
                <p className="text-xs text-gray-500">{t.desc}</p>
              </div>
            ))}
          </div>
        </section>

        {/* How to print */}
        <section className="bg-gray-50 rounded-3xl p-8">
          <h2 className="font-display text-3xl text-gray-800 mb-4">How to Print Your Chart</h2>
          <ol className="space-y-4">
            {[
              { n: '1', text: 'Open the Chore Chart Generator above.' },
              { n: '2', text: 'Enter your child\'s name, pick an age group, and select up to 7 chores.' },
              { n: '3', text: 'Choose a theme and optionally add a reward goal.' },
              { n: '4', text: 'Click Download PDF — or click Print to skip saving the file.' },
              { n: '5', text: 'Print on any home printer using A4 or US Letter paper.' },
            ].map(s => (
              <li key={s.n} className="flex items-start gap-4">
                <span className="w-8 h-8 rounded-full bg-indigo-600 text-white font-bold text-sm flex items-center justify-center flex-shrink-0 mt-0.5">
                  {s.n}
                </span>
                <p className="text-gray-700 leading-relaxed">{s.text}</p>
              </li>
            ))}
          </ol>
        </section>

        {/* FAQ */}
        <section>
          <h2 className="font-display text-3xl text-gray-800 mb-6">Questions &amp; Answers</h2>
          <div className="space-y-4">
            {faqs.map(faq => (
              <div key={faq.q} className="bg-white rounded-2xl p-6 border border-gray-100">
                <h3 className="font-bold text-gray-800 mb-2">{faq.q}</h3>
                <p className="text-gray-600 text-sm leading-relaxed">{faq.a}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Internal links */}
        <section className="bg-indigo-50 rounded-3xl p-8 border border-indigo-100">
          <h2 className="font-bold text-gray-800 text-xl mb-4">More Free Tools</h2>
          <div className="space-y-3">
            <Link href="/chore-chart-generator" className="flex items-center gap-3 text-indigo-700 font-semibold hover:underline">
              <span>📋</span> Chore Chart Generator
            </Link>
            <Link href="/reward-chart-generator" className="flex items-center gap-3 text-indigo-700 font-semibold hover:underline">
              <span>🌟</span> Reward Chart Generator
            </Link>
            <Link href="/chores-for-kids-by-age" className="flex items-center gap-3 text-indigo-700 font-semibold hover:underline">
              <span>📚</span> Age-Appropriate Chores Guide
            </Link>
          </div>
        </section>

        {/* Ad before CTA */}
        <AdUnit slot={process.env.NEXT_PUBLIC_AD_SLOT_CONTENT} format="horizontal" className="my-6" />

        {/* CTA */}
        <div className="text-center">
          <Link
            href="/chore-chart-generator"
            className="inline-block bg-indigo-600 hover:bg-indigo-700 text-white font-bold px-10 py-4 rounded-2xl text-lg transition-colors shadow-md"
          >
            📋 Create My Free Printable Chart
          </Link>
          <p className="mt-3 text-gray-400 text-sm">Instant PDF download · No login required · Free forever</p>
        </div>
      </div>
    </>
  )
}
